language: python
cache: pip

python:
  - "3.6"

install:
  - apt-get install npm
  - pip install mypy
  - pip install -r requirements.txt
  - git clone git clone https://github.com/sdevalapurkar/battlesnake-test-suite.git
  - cd battlesnake-test-suite && npm install

script:
  - python -m battlesnake &
  - npm run test --host=localhost --port=5000

notifications:
  email:
    on_failure: change
    on_success: never